server:
  address: 192.168.65.178
  port: 9100
spring:
  redis:
    database: 0
    host: 192.168.65.227
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 50
        min-idle: 10
        max-wait: 1000

